[project]
name = "tinygp"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "tinygrad",
]

[tool.uv.sources]
tinygrad = { path = "tinygrad", editable = true }

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
